title: Tk Asme Api Ingenieria
description: "Empresa metal mecánica de construcción y reparación de tanques a presión, redes tuberías de conducción de hidrocarburos, gas y obras complementarias en Colombia. Medicion de espesores, prueba hidrostatica."
baseurl: ""
url: "https://tkasme.com"
social:
  name: Global SWAI
  links:
    - https://www.instagram.com/global_swai
author:
  name: Tk Asme API
  image: /assets/logo_small.png
  email: tkasme@yahoo.es
  show_on_post: true
logo: /assets/logo_small.png
lang: es
google_analytics: "UA-68913933-1" #Google analytics code in the format XX-nnnnnnnn-n

# Color the browser elements #
color-browser: "#13123d"
apple-status-bar-style: "black"

permalink: /:categories/:title/
sass:
  style: compressed
markdown: kramdown

collections:
  iframes:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
  - node_modules
  - package-lock.json
