title: Tk Asme Api Ingenieria
description: "Empresa metal mecánica de construcción y reparación de tanques a presión, redes tuberías de conducción de hidrocarburos, gas y obras complementarias en Colombia, con sede en Bucaramanga. Medicion de espesores, prueba hidrostatica."
baseurl: ""
url: "https://tkasme.com"
#url: "http://tkasme.batcave.net"
social:
  name: Tk Asme API Ingenieria
author:
  name: Tk Asme API Ingenieria
  image: /assets/images/logo.png
  email: tkasme@yahoo.es
  show_on_post: true
logo: /assets/images/logo.png
lang: es
google_analytics: "UA-68913933-1" #Google analytics code in the format XX-nnnnnnnn-n
google_site_verification: 'O_ge7Syjw68Ie97e71BKDaKGpo01aToquytDxDmtHII'

# Color the browser elements #
color-browser: "#13123d"
apple-status-bar-style: "black"

permalink: /:categories/:title/
sass:
  style: compressed
markdown: kramdown

collections:
  iframes:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
  - node_modules
  - package-lock.json
  - package.json
  - gulpfile.js
