title: Tk Asme Api Ingenieria
description: "Empresa metal mecánica de construcción y reparación de tanques a presión, redes tuberías de conducción de hidrocarburos, gas y obras complementarias en Colombia. Medicion de espesores, prueba hidrostatica."
google_analytics: "UA-68913933-1" #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://tkasme.com" # the base hostname & protocol for your site, e.g. http://example.com

# Site settings
title: Tk Asme Api

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Zona Industrial Km 2 Cr0 3-57 Vía Chimitá
  - line: Bucaramanga, Santander, Colombia

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-minibundle
  - jekyll-gist 
  - jekyll-assets

# minifier settings
minibundle:
  minifier_commands:
    js: uglifyjs -
    source_dir: _assets/javascripts
    destination_path: /assets/head
    assets:
    - jquery-2.1.4
    - bootstrap
    - slick
    - slides
    - layout
    - flickr-import
    attributes:
    async: async

assets:
  compress:
    css: true
  js_compressor:  uglifier
  css_compressor: scss
  features:
    liquid: true

