# Site settings

title: Tkasme api ingenieria
description: "Empresa metal mecánica de construcción y reparación de tanques a presión, redes tuberías de conducción de hidrocarburos, gas y obras complementarias en Colombia. Medicion de espesores, prueba hidrostatica."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tkasme.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Cristian Perez
logo: /img/logo_square.svg

social:
  name: Tk Asme Api Ingenieria
  links:
    - https://plus.google.com/117521031029555557198

google_analytics: "UA-68913933-1" #Google analytics code in the format XX-nnnnnnnn-n
google_site_verification: "6A_MGnrnswlpSrE8HkL03McCaZMjmAT_1jHhL1t1YqE"

#webmaster_verifications:
#  google: 1234
#  bing: 1234
#  alexa: 1234
#  yandex: 1234
#
lang: es_ES
 
# Build settings
sass:
    style: compressed
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
exclude:
  - drafts
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
 
#defaults:
#    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}
#
#include:
#  - _pages
